### ISSUE TITLE
Any chance for a version that is swift 2.2 compatible? :) Maybe an older one.. :)?

### ISSUE THREAD

**Issue by nharbo** [thehung111/NHRangeSlider#3]
I would love to use your slider, but my project is in swift 2.2 :/ Any chances that it will work somehow? I tried with version 0.1, but it doesn't build

**Comment by thehung111** [comment]
The project is built with Swift 3.0+ only so it will give errors if you use 2.2. The syntax (e.g. method names) has changed in the latest Swift versions.

You can copy the source files manually into your project and fix the syntax errors. It should be quite easy/minor to do so.

**Comment by nharbo** [comment]
Hey again,
Thanks for your reply.. I've forked your project and converted it into Swift 2.2 - but the files wont draw in the StoryBoard, and either in my application. Is there any chance you can have a look at the code, and see if anything's missing? The files compile properly..
https://github.com/nharbo/NSRangeSliderSwift2.2

Please let me know, I really need this to work :-) Thanks a lot! 👍

**Comment by nharbo** [comment]
It might be because of the "open"-statements, but I'm not sure how to make this in Swift 2.2 :/

**Comment by thehung111** [comment]
yes, open is a new keyword in Swift 3. You can replace with public. Just make sure that there is no compilation error. I think it would be easier if you create your own Xcode project and modify the example. And no I am not interested in viewing older codes :) Swift 4 is coming soon men.
