### ISSUE TITLE
Sliding logic error with minimum gap between thumbs

### ISSUE THREAD

**Issue by anthonysalvato3** [thehung111/NHRangeSlider#4]
Easiest to reproduce when gapBetweenThumbs = 0. Steps to reproduce:

1. Slide thumbs as close together as possible
2. Slide thumb left and right without releasing your finger
3. Instead of one thumb sliding in both directions, both thumbs will each slide in their corresponding direction

**Comment by thehung111** [comment]
Hi, gapBetweenThumbs must be greater than 0. Otherwise, the thumbs can overlap :) I will specify  this constraint later :)

**Comment by felixdkatt** [comment]
I tried it with the following edited code in the begin tracking method and seems to fix the issue

override open func beginTracking(_ touch: UITouch, with event: UIEvent?) -> Bool {
        previouslocation = touch.location(in: self)
        
        // set highlighted positions for lower and upper thumbs
        if lowerThumbLayer.frame.contains(previouslocation) {
            lowerThumbLayer.highlighted = true
        }
        
        if upperThumbLayer.frame.contains(previouslocation) {
            upperThumbLayer.highlighted = true
        }
		
		if upperThumbLayer.highlighted && lowerThumbLayer.highlighted{
			if upperValue == maximumValue {
				upperThumbLayer.highlighted = false
			}else{
				lowerThumbLayer.highlighted = false
			}
		}
        
        return lowerThumbLayer.highlighted || upperThumbLayer.highlighted
    }

**Comment by felixdkatt** [comment]
Sorry I didn't do a pull request let me know if you'd like me to or if you just want to change it yourself.
