### ISSUE TITLE
Problem adding NHRangeSliderView via Storyboard

### ISSUE THREAD

**Issue by rcmstark** [thehung111/NHRangeSlider#6]
Can you add an example in your demo app? 

When I tried to add a UIView in storyboard an change it to be NHRangeSliderView class, it doesn't work. I'm only able to add it programmatically.

**Comment by eyeezzi** [comment]
@rcmcastro 
1. This is how you do it: drag a normal `UIView` into a view controller.
2. Select the view you just dropped and go to the **Identity Inspector**. In the **Custom Class** section, change the **Class** and **Module** values to `NHRangeSlider`, and viola!. See attached image, hope this helps...it's the same approach for all these controls that claim Storyboard compatibility. 

![superscreenshot 2017-4-27 3-15-28](https://cloud.githubusercontent.com/assets/9389872/25478980/206365ba-2af8-11e7-97b9-c6f0ab529c51.png)
