### ISSUE TITLE
Remove upper and lower labels on thumbs

### ISSUE THREAD

**Issue by mding5692** [thehung111/NHRangeSlider#7]
Hi, been using the RangeSlider for my app, is it possible to remove the upper and lower labels on the thumbs?

What I've been using is just setting displayformat for both to be null strings, is there a better way?

**Comment by mding5692** [comment]
I guess for now, to remove thumb labels, set each displayFormat = ""

**Comment by thehung111** [comment]
you can access lowerLabel, upperLabel property and hide them. If you really want them gone you need to subclass NHRangeSliderView and override the layoutSubviews method. The frames for the labels are set there.
