### ISSUE TITLE
Problem accessing upperValue and lowerValue

### ISSUE THREAD

**Issue by mding5692** [thehung111/NHRangeSlider#8]
Hi there, I am making my own custom labels displaying upperValue and lowerValue when the sliderValueChanged method is called, except I can't get the changed upperValue and lowerValues

![screen shot 2017-05-07 at 5 21 03 pm](https://cloud.githubusercontent.com/assets/9067177/25785239/a151b59c-3349-11e7-8b2b-254ae07ef67c.png)

^See above for my code

**Comment by thehung111** [comment]
you can access the value via sliderView.rangeSlider!.upperValue . sliderView.upperValue is meant for writing, not reading. I will fix that later.
